server:
  port: 80
  
spring:
  mvc:
    view:
      suffix: .html
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant-path-matcher
      
logging:
  config: classpath:spring-logback.xml
